cc_test(
    name = "core_test",
    srcs = ["core_test.cc"],
    copts = ["-Iexternal/gtest/googletest/include"],
    deps = [
        "@gtest//:gtest",
        "@gtest//:gtest_main",
        "//src:core_lib",
    ],
)
