cc_binary(
    name = "anvm",
    srcs = ["main.cc"],
    deps = [
        "//src:core_lib",
        "//src/util:log_lib",
        "//src/util:program_reader_lib",
    ],
    visibility = ["//visibility:public"],
)
