#!/usr/bin/python

import sys

if len(sys.argv) != 3:
    print "usage: %s <ClassName> <out_directory>" % (sys.argv[0])
    exit(1)

class_name = sys.argv[1]
out_dir = sys.argv[2]

file_name = ""
file_define = ""
need_blank = False
for i in range(len(class_name)):
    if i != 0 and class_name[i].isupper():
        file_name += "_"
        file_define += "_"
    file_name += class_name[i].lower()
    file_define += class_name[i].upper()

h_file_name = out_dir + "/" + file_name + ".h"
h_file_name = h_file_name.replace("//", "/")
c_file_name = out_dir + "/" + file_name + ".cc"
c_file_name = c_file_name.replace("//", "/")

h_file_define = "ANVM_"
h_file_define += out_dir.upper().replace("src/", "").replace("/", "_")
h_file_define += file_define
h_file_define += "_H_"

h_file_contents = """#ifndef %s
#define %s

class %s {
};

#endif // %s
"""

with open(h_file_name, "w") as f:
    f.write(h_file_contents % (h_file_define, h_file_define, class_name, h_file_define))

c_file_contents = """#include "%s"
"""

with open(c_file_name, "w") as f:
    f.write(c_file_contents % (h_file_name))
