cc_library(
    name = "core_lib",
    srcs = [
        "cpu.cc",
        "program.cc",
        "system.cc",
    ],
    hdrs = [
        "cpu.h",
        "program.h",
        "system.h",
    ],
    visibility = ["//visibility:public"],
)
