cc_library(
    name = "core_lib",
    srcs = [
        "cpu.cc",
        "program.cc",
        "system.cc",
        "process.cc",
    ],
    hdrs = [
        "cpu.h",
        "program.h",
        "system.h",
        "process.h",
    ],
    copts = [
        "-Wall",
        "-Werror",
        "-g",
        "-ggdb",
        "-O0",
    ],
    visibility = ["//visibility:public"],
)
